/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.cco006.thesims.view;

import br.edu.unifei.cco006.thesims.dao.CasaDao;
import br.edu.unifei.cco006.thesims.dao.CidadeDao;
import br.edu.unifei.cco006.thesims.dao.FonteDados;
import br.edu.unifei.cco006.thesims.modelo.Casa;
import br.edu.unifei.cco006.thesims.modelo.Cidade;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class CasaInserir extends javax.swing.JFrame {

    private final EntityManager em = FonteDados.createEntityManager();
    private final CasaDao cdao = new CasaDao(em);
    private Casa casa;
    private final CidadeDao cidadeDao = new CidadeDao(em);
    private Cidade cidade;
    
    /**
     * Creates new form InsereCidade
     */
    public CasaInserir() {
        initComponents();
       
        List<Cidade> lCidade = cidadeDao.findAll();
        for (Cidade c : lCidade) {
             cbxCidade.addItem(c.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabOperacoes = new javax.swing.JTabbedPane();
        panInserir = new javax.swing.JPanel();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        lblCorParede = new javax.swing.JLabel();
        lblTam = new javax.swing.JLabel();
        txtCorParede = new javax.swing.JTextField();
        txtTam = new javax.swing.JTextField();
        lblCorTelhado = new javax.swing.JLabel();
        txtCorTelhado = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        cbxCidade = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblPreco.setText("Preço:");

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        lblCorParede.setText("Cor parede:");

        lblTam.setText("Tamanho");

        lblCorTelhado.setText("Cor telhado:");

        lblCidade.setText("Cidade:");

        javax.swing.GroupLayout panInserirLayout = new javax.swing.GroupLayout(panInserir);
        panInserir.setLayout(panInserirLayout);
        panInserirLayout.setHorizontalGroup(
            panInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInserirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panInserirLayout.createSequentialGroup()
                        .addComponent(lblCorTelhado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCorTelhado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panInserirLayout.createSequentialGroup()
                        .addGroup(panInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorParede)
                            .addComponent(lblTam)
                            .addComponent(lblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInserir)
                            .addComponent(txtCorParede, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPreco, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))))
                    .addGroup(panInserirLayout.createSequentialGroup()
                        .addComponent(lblCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        panInserirLayout.setVerticalGroup(
            panInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInserirLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTam)
                    .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorParede)
                    .addComponent(txtCorParede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorTelhado)
                    .addComponent(txtCorTelhado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnInserir)
                .addGap(40, 40, 40))
        );

        tabOperacoes.addTab("Inserir", panInserir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabOperacoes, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabOperacoes, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        
        cidade = cidadeDao.findByKey(cbxCidade.getSelectedItem().toString());
        
        casa = new Casa();
        casa.setPreco(Float.parseFloat(txtPreco.getText()));
        casa.setTamanho(Integer.parseInt(txtTam.getText()));
        casa.setCorParede(txtCorParede.getText());
        casa.setCorTelhado(txtCorTelhado.getText());

        cdao.create(casa);
        cidade.getConstrucoes().add(casa);
        cidadeDao.update(cidade);
        
        JOptionPane.showMessageDialog(
                this, "Casa criada. \nPreço: "+ casa.getPreco() + "\nTamanho: "+ casa.getTamanho() +
                        "\nCor parede: " + casa.getCorParede() +"\nCor telhado: " + casa.getCorTelhado());
        txtPreco.setText("");
        txtCorParede.setText("");
        txtCorTelhado.setText("");
        txtTam.setText("");
        
    }//GEN-LAST:event_btnInserirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.JComboBox<String> cbxCidade;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCorParede;
    private javax.swing.JLabel lblCorTelhado;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTam;
    private javax.swing.JPanel panInserir;
    private javax.swing.JTabbedPane tabOperacoes;
    private javax.swing.JTextField txtCorParede;
    private javax.swing.JTextField txtCorTelhado;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtTam;
    // End of variables declaration//GEN-END:variables
}
