/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.cco006.thesims.view;

import br.edu.unifei.cco006.thesims.dao.CasaDao;
import br.edu.unifei.cco006.thesims.dao.ComodoDao;
import br.edu.unifei.cco006.thesims.dao.FonteDados;
import br.edu.unifei.cco006.thesims.modelo.Casa;
import br.edu.unifei.cco006.thesims.modelo.Comodo;
import br.edu.unifei.cco006.thesims.modelo.ComodoEnum;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class ComodoInserir extends javax.swing.JFrame {
    
    private final EntityManager em = FonteDados.createEntityManager();
    private final ComodoDao cdao = new ComodoDao(em);
    private Comodo comodo;
    private final CasaDao casaDao = new CasaDao(em);
    private Casa casa;
    
    
    /**
     * Creates new form ComodoInserir
     */
    public ComodoInserir() {
        initComponents();
        
        List<Integer> l = casaDao.buscaCasa();
        for (int cod : l) {
            cbxCasa.addItem(""+cod);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbxCasa = new javax.swing.JComboBox<>();
        lblTamanho = new javax.swing.JLabel();
        txtTamanho = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTipo.setText("Tipo:");

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QUARTO", "SALA", "COZINHA", "BANHEIRO", "SERVICO", "ESCRITORIO", "QUINTAL" }));

        jLabel1.setText("Casa:");

        lblTamanho.setText("Tamanho:");

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTamanho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInserir)
                            .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamanho))
                .addGap(18, 18, 18)
                .addComponent(btnInserir)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        comodo = new Comodo();
        if(cbxTipo.getSelectedItem().toString().equals("QUARTO")) {
            comodo.setComodo(ComodoEnum.QUARTO);
        } else if(cbxTipo.getSelectedItem().toString().equals("SALA")) {
            comodo.setComodo(ComodoEnum.SALA);
        } else if(cbxTipo.getSelectedItem().toString().equals("COZINHA")) {
            comodo.setComodo(ComodoEnum.COZINHA);
        } else if(cbxTipo.getSelectedItem().toString().equals("BANHEIRO")) {
            comodo.setComodo(ComodoEnum.BANHEIRO);
        } else if(cbxTipo.getSelectedItem().toString().equals("SERVICO")) {
            comodo.setComodo(ComodoEnum.SERVICO);
        } else if(cbxTipo.getSelectedItem().toString().equals("ESCRITORIO")) {
            comodo.setComodo(ComodoEnum.ESCRITORIO);
        } else if(cbxTipo.getSelectedItem().toString().equals("QUINTAL")) {
            comodo.setComodo(ComodoEnum.QUINTAL);
        }
        comodo.setTamanho(Integer.parseInt(txtTamanho.getText()));
        cdao.create(comodo);

        casa = casaDao.findByKey(Integer.parseInt(
                cbxCasa.getSelectedItem().toString()));
        casa.getComodo().add(comodo);
        casaDao.update(casa);
        
        JOptionPane.showMessageDialog(
                this, " Comodo criado. \nTamanho: "+ comodo.getTamanho());
        
    }//GEN-LAST:event_btnInserirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.JComboBox<String> cbxCasa;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtTamanho;
    // End of variables declaration//GEN-END:variables
}
