/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.cco006.thesims.view;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author maria
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        barInicial = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mnuCidade = new javax.swing.JMenu();
        itmInsCidade = new javax.swing.JMenuItem();
        itmExcCidade = new javax.swing.JMenuItem();
        mnuFamilia = new javax.swing.JMenu();
        itmInsFamilia = new javax.swing.JMenuItem();
        itmAltFamilia = new javax.swing.JMenuItem();
        mnuCasa = new javax.swing.JMenu();
        itnInsCasa = new javax.swing.JMenuItem();
        itnExcCasa = new javax.swing.JMenuItem();
        mnuComodo = new javax.swing.JMenu();
        itmInsComodo = new javax.swing.JMenuItem();
        itmExcComodo = new javax.swing.JMenuItem();
        mnuPessoa = new javax.swing.JMenu();
        itmInsPessoa = new javax.swing.JMenuItem();
        itmExcPessoa = new javax.swing.JMenuItem();
        mnuVest = new javax.swing.JMenu();
        itmInsVest = new javax.swing.JMenuItem();
        itmExcVest = new javax.swing.JMenuItem();
        mnuTrabalho = new javax.swing.JMenu();
        itmInsTrabalho = new javax.swing.JMenuItem();
        itmExcluir = new javax.swing.JMenuItem();
        mnuObjeto = new javax.swing.JMenu();
        itmInsObjeto = new javax.swing.JMenuItem();
        itmExcObjeto = new javax.swing.JMenuItem();
        mnuMobilia = new javax.swing.JMenu();
        itmInsMobilia = new javax.swing.JMenuItem();
        itmExcMobilia = new javax.swing.JMenuItem();
        mnuLugar = new javax.swing.JMenu();
        itmInsLugar = new javax.swing.JMenuItem();
        itmExcLugar = new javax.swing.JMenuItem();
        mnuEvento = new javax.swing.JMenu();
        itmInsEvento = new javax.swing.JMenuItem();
        itmExcEvento = new javax.swing.JMenuItem();
        mnuAcoes = new javax.swing.JMenu();
        mnuAlimentar = new javax.swing.JMenu();
        itmInsAlimento = new javax.swing.JMenuItem();
        mnuMovimentar = new javax.swing.JMenu();
        itmInsMovimentar = new javax.swing.JMenuItem();
        mnuLazer = new javax.swing.JMenu();
        itmInsLazer = new javax.swing.JMenuItem();
        mnuRelacionamento = new javax.swing.JMenu();
        itmInsRelacionamento = new javax.swing.JMenuItem();
        mnuTarefa = new javax.swing.JMenu();
        itmInsTarefa = new javax.swing.JMenuItem();
        itmExcAcao = new javax.swing.JMenuItem();
        mnuNecessidade = new javax.swing.JMenu();
        itmInsNecessidade = new javax.swing.JMenuItem();
        itmExcNecessidade = new javax.swing.JMenuItem();
        mnuHabilidade = new javax.swing.JMenu();
        itmInsHabilidade = new javax.swing.JMenuItem();
        itmExcHabilidade = new javax.swing.JMenuItem();
        mnuSobre = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuCadastro.setText("Cadastro");

        mnuCidade.setText("Cidade");

        itmInsCidade.setText("Inserir");
        itmInsCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsCidadeActionPerformed(evt);
            }
        });
        mnuCidade.add(itmInsCidade);

        itmExcCidade.setText("Excluir");
        itmExcCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcCidadeActionPerformed(evt);
            }
        });
        mnuCidade.add(itmExcCidade);

        mnuCadastro.add(mnuCidade);

        mnuFamilia.setText("Familia");

        itmInsFamilia.setText("Insere Familia");
        itmInsFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsFamiliaActionPerformed(evt);
            }
        });
        mnuFamilia.add(itmInsFamilia);

        itmAltFamilia.setText("Altera Familia");
        itmAltFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAltFamiliaActionPerformed(evt);
            }
        });
        mnuFamilia.add(itmAltFamilia);

        mnuCadastro.add(mnuFamilia);

        mnuCasa.setText("Casa");

        itnInsCasa.setText("Inserir");
        itnInsCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnInsCasaActionPerformed(evt);
            }
        });
        mnuCasa.add(itnInsCasa);

        itnExcCasa.setText("Excluir");
        itnExcCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnExcCasaActionPerformed(evt);
            }
        });
        mnuCasa.add(itnExcCasa);

        mnuCadastro.add(mnuCasa);

        mnuComodo.setText("Comodo");

        itmInsComodo.setText("Inserir");
        itmInsComodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsComodoActionPerformed(evt);
            }
        });
        mnuComodo.add(itmInsComodo);

        itmExcComodo.setText("Excluir");
        itmExcComodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcComodoActionPerformed(evt);
            }
        });
        mnuComodo.add(itmExcComodo);

        mnuCadastro.add(mnuComodo);

        mnuPessoa.setText("Pessoa");

        itmInsPessoa.setText("Inserir");
        itmInsPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsPessoaActionPerformed(evt);
            }
        });
        mnuPessoa.add(itmInsPessoa);

        itmExcPessoa.setText("Excluir");
        itmExcPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcPessoaActionPerformed(evt);
            }
        });
        mnuPessoa.add(itmExcPessoa);

        mnuCadastro.add(mnuPessoa);

        mnuVest.setText("Vestuário");

        itmInsVest.setText("Inserir");
        itmInsVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsVestActionPerformed(evt);
            }
        });
        mnuVest.add(itmInsVest);

        itmExcVest.setText("Excluir");
        itmExcVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcVestActionPerformed(evt);
            }
        });
        mnuVest.add(itmExcVest);

        mnuCadastro.add(mnuVest);

        mnuTrabalho.setText("Trabalho");

        itmInsTrabalho.setText("Inserir");
        itmInsTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsTrabalhoActionPerformed(evt);
            }
        });
        mnuTrabalho.add(itmInsTrabalho);

        itmExcluir.setText("Excluir");
        itmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirActionPerformed(evt);
            }
        });
        mnuTrabalho.add(itmExcluir);

        mnuCadastro.add(mnuTrabalho);

        mnuObjeto.setText("Objeto");

        itmInsObjeto.setText("Inserir");
        itmInsObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsObjetoActionPerformed(evt);
            }
        });
        mnuObjeto.add(itmInsObjeto);

        itmExcObjeto.setText("Excluir");
        itmExcObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcObjetoActionPerformed(evt);
            }
        });
        mnuObjeto.add(itmExcObjeto);

        mnuCadastro.add(mnuObjeto);

        mnuMobilia.setText("Mobilia");

        itmInsMobilia.setText("Inserir");
        itmInsMobilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsMobiliaActionPerformed(evt);
            }
        });
        mnuMobilia.add(itmInsMobilia);

        itmExcMobilia.setText("Excluir");
        itmExcMobilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcMobiliaActionPerformed(evt);
            }
        });
        mnuMobilia.add(itmExcMobilia);

        mnuCadastro.add(mnuMobilia);

        mnuLugar.setText("Lugar");

        itmInsLugar.setText("Inserir");
        itmInsLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsLugarActionPerformed(evt);
            }
        });
        mnuLugar.add(itmInsLugar);

        itmExcLugar.setText("Excluir");
        itmExcLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcLugarActionPerformed(evt);
            }
        });
        mnuLugar.add(itmExcLugar);

        mnuCadastro.add(mnuLugar);

        mnuEvento.setText("Evento");

        itmInsEvento.setText("Inserir");
        itmInsEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsEventoActionPerformed(evt);
            }
        });
        mnuEvento.add(itmInsEvento);

        itmExcEvento.setText("Excluir");
        itmExcEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcEventoActionPerformed(evt);
            }
        });
        mnuEvento.add(itmExcEvento);

        mnuCadastro.add(mnuEvento);

        mnuAcoes.setText("Ações");

        mnuAlimentar.setText("Alimentar");

        itmInsAlimento.setText("Inserir");
        itmInsAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsAlimentoActionPerformed(evt);
            }
        });
        mnuAlimentar.add(itmInsAlimento);

        mnuAcoes.add(mnuAlimentar);

        mnuMovimentar.setText("Movimentar");

        itmInsMovimentar.setText("Inserir");
        itmInsMovimentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsMovimentarActionPerformed(evt);
            }
        });
        mnuMovimentar.add(itmInsMovimentar);

        mnuAcoes.add(mnuMovimentar);

        mnuLazer.setText("Lazer");

        itmInsLazer.setText("Inserir");
        itmInsLazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsLazerActionPerformed(evt);
            }
        });
        mnuLazer.add(itmInsLazer);

        mnuAcoes.add(mnuLazer);

        mnuRelacionamento.setText("Relacionamento");

        itmInsRelacionamento.setText("Inserir");
        itmInsRelacionamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsRelacionamentoActionPerformed(evt);
            }
        });
        mnuRelacionamento.add(itmInsRelacionamento);

        mnuAcoes.add(mnuRelacionamento);

        mnuTarefa.setText("Tarefa");

        itmInsTarefa.setText("Inserir");
        itmInsTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsTarefaActionPerformed(evt);
            }
        });
        mnuTarefa.add(itmInsTarefa);

        mnuAcoes.add(mnuTarefa);

        itmExcAcao.setText("Excluir");
        itmExcAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcAcaoActionPerformed(evt);
            }
        });
        mnuAcoes.add(itmExcAcao);

        mnuCadastro.add(mnuAcoes);

        mnuNecessidade.setText("Necessidade");

        itmInsNecessidade.setText("Inserir");
        itmInsNecessidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsNecessidadeActionPerformed(evt);
            }
        });
        mnuNecessidade.add(itmInsNecessidade);

        itmExcNecessidade.setText("Excluir");
        itmExcNecessidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcNecessidadeActionPerformed(evt);
            }
        });
        mnuNecessidade.add(itmExcNecessidade);

        mnuCadastro.add(mnuNecessidade);

        mnuHabilidade.setText("Habilidade");

        itmInsHabilidade.setText("Inserir");
        itmInsHabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInsHabilidadeActionPerformed(evt);
            }
        });
        mnuHabilidade.add(itmInsHabilidade);

        itmExcHabilidade.setText("Excluir");
        itmExcHabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcHabilidadeActionPerformed(evt);
            }
        });
        mnuHabilidade.add(itmExcHabilidade);

        mnuCadastro.add(mnuHabilidade);

        barInicial.add(mnuCadastro);

        mnuSobre.setText("Sobre");
        barInicial.add(mnuSobre);

        setJMenuBar(barInicial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmInsFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsFamiliaActionPerformed
        // TODO add your handling code here:
                /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamiliaInserir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmInsFamiliaActionPerformed

    private void itmAltFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAltFamiliaActionPerformed

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamiliaAlterar().setVisible(true);
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_itmAltFamiliaActionPerformed

    private void itmInsCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsCidadeActionPerformed
        // TODO add your handling code here:
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CidadeInserir().setVisible(true);
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_itmInsCidadeActionPerformed

    private void itmExcCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcCidadeActionPerformed
        // TODO add your handling code here:
                /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CidadeExcluir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmExcCidadeActionPerformed

    private void itnInsCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnInsCasaActionPerformed
        // TODO add your handling code here:
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasaInserir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itnInsCasaActionPerformed

    private void itmInsComodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsComodoActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComodoInserir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmInsComodoActionPerformed

    private void itnExcCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnExcCasaActionPerformed
        // TODO add your handling code here:
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasaExcluir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itnExcCasaActionPerformed

    private void itmExcComodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcComodoActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComodoExcluir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmExcComodoActionPerformed

    private void itmInsPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsPessoaActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoaInserir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmInsPessoaActionPerformed

    private void itmExcPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcPessoaActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoaExcluir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmExcPessoaActionPerformed

    private void itmInsVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsVestActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VestuarioInserir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmInsVestActionPerformed

    private void itmExcVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcVestActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VestuarioExcluir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmExcVestActionPerformed

    private void itmInsTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsTrabalhoActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrabalhoInserir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmInsTrabalhoActionPerformed

    private void itmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrabalhoExcluir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmExcluirActionPerformed

    private void itmInsObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsObjetoActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObjetoInserir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmInsObjetoActionPerformed

    private void itmExcObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcObjetoActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObjetoExcluir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmExcObjetoActionPerformed

    private void itmInsMobiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsMobiliaActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobiliaInserir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmInsMobiliaActionPerformed

    private void itmExcMobiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcMobiliaActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobiliaExcluir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmExcMobiliaActionPerformed

    private void itmInsLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsLugarActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LugarInserir().setVisible(true);
            }
        });    
    }//GEN-LAST:event_itmInsLugarActionPerformed

    private void itmExcLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcLugarActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LugarExcluir().setVisible(true);
            }
        }); 
    }//GEN-LAST:event_itmExcLugarActionPerformed

    private void itmInsEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsEventoActionPerformed
        // TODO add your handling code here:
           java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventoInserir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmInsEventoActionPerformed

    private void itmExcEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcEventoActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventoExcluir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmExcEventoActionPerformed

    private void itmInsAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsAlimentoActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlimentarInserir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmInsAlimentoActionPerformed

    private void itmInsMovimentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsMovimentarActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimentoInserir().setVisible(true);
            }
        });   
    }//GEN-LAST:event_itmInsMovimentarActionPerformed

    private void itmInsLazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsLazerActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LazerInserir().setVisible(true);
            }
        });  
    }//GEN-LAST:event_itmInsLazerActionPerformed

    private void itmInsRelacionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsRelacionamentoActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelacionamentoInserir().setVisible(true);
            }
        }); 
    }//GEN-LAST:event_itmInsRelacionamentoActionPerformed

    private void itmInsTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsTarefaActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarefaInserir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmInsTarefaActionPerformed

    private void itmExcAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcAcaoActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcaoExcluir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmExcAcaoActionPerformed

    private void itmInsNecessidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsNecessidadeActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NecessidadeInserir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmInsNecessidadeActionPerformed

    private void itmExcNecessidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcNecessidadeActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NecessidadeExcluir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmExcNecessidadeActionPerformed

    private void itmInsHabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInsHabilidadeActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HabilidadeInserir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmInsHabilidadeActionPerformed

    private void itmExcHabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcHabilidadeActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HabilidadeExcluir().setVisible(true);
            }
        });
    }//GEN-LAST:event_itmExcHabilidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barInicial;
    private javax.swing.JMenuItem itmAltFamilia;
    private javax.swing.JMenuItem itmExcAcao;
    private javax.swing.JMenuItem itmExcCidade;
    private javax.swing.JMenuItem itmExcComodo;
    private javax.swing.JMenuItem itmExcEvento;
    private javax.swing.JMenuItem itmExcHabilidade;
    private javax.swing.JMenuItem itmExcLugar;
    private javax.swing.JMenuItem itmExcMobilia;
    private javax.swing.JMenuItem itmExcNecessidade;
    private javax.swing.JMenuItem itmExcObjeto;
    private javax.swing.JMenuItem itmExcPessoa;
    private javax.swing.JMenuItem itmExcVest;
    private javax.swing.JMenuItem itmExcluir;
    private javax.swing.JMenuItem itmInsAlimento;
    private javax.swing.JMenuItem itmInsCidade;
    private javax.swing.JMenuItem itmInsComodo;
    private javax.swing.JMenuItem itmInsEvento;
    private javax.swing.JMenuItem itmInsFamilia;
    private javax.swing.JMenuItem itmInsHabilidade;
    private javax.swing.JMenuItem itmInsLazer;
    private javax.swing.JMenuItem itmInsLugar;
    private javax.swing.JMenuItem itmInsMobilia;
    private javax.swing.JMenuItem itmInsMovimentar;
    private javax.swing.JMenuItem itmInsNecessidade;
    private javax.swing.JMenuItem itmInsObjeto;
    private javax.swing.JMenuItem itmInsPessoa;
    private javax.swing.JMenuItem itmInsRelacionamento;
    private javax.swing.JMenuItem itmInsTarefa;
    private javax.swing.JMenuItem itmInsTrabalho;
    private javax.swing.JMenuItem itmInsVest;
    private javax.swing.JMenuItem itnExcCasa;
    private javax.swing.JMenuItem itnInsCasa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu mnuAcoes;
    private javax.swing.JMenu mnuAlimentar;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenu mnuCasa;
    private javax.swing.JMenu mnuCidade;
    private javax.swing.JMenu mnuComodo;
    private javax.swing.JMenu mnuEvento;
    private javax.swing.JMenu mnuFamilia;
    private javax.swing.JMenu mnuHabilidade;
    private javax.swing.JMenu mnuLazer;
    private javax.swing.JMenu mnuLugar;
    private javax.swing.JMenu mnuMobilia;
    private javax.swing.JMenu mnuMovimentar;
    private javax.swing.JMenu mnuNecessidade;
    private javax.swing.JMenu mnuObjeto;
    private javax.swing.JMenu mnuPessoa;
    private javax.swing.JMenu mnuRelacionamento;
    private javax.swing.JMenu mnuSobre;
    private javax.swing.JMenu mnuTarefa;
    private javax.swing.JMenu mnuTrabalho;
    private javax.swing.JMenu mnuVest;
    // End of variables declaration//GEN-END:variables
}
