/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.cco006.thesims.view;

import br.edu.unifei.cco006.thesims.dao.CidadeDao;
import br.edu.unifei.cco006.thesims.dao.EventoDao;
import br.edu.unifei.cco006.thesims.dao.FonteDados;
import br.edu.unifei.cco006.thesims.dao.LugarDao;
import br.edu.unifei.cco006.thesims.modelo.Cidade;
import br.edu.unifei.cco006.thesims.modelo.Construcao;
import br.edu.unifei.cco006.thesims.modelo.Evento;
import br.edu.unifei.cco006.thesims.modelo.Lugar;
import br.edu.unifei.cco006.thesims.modelo.LugarEnum;
import java.time.LocalDateTime;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class LugarExcluir extends javax.swing.JFrame {

    private final EntityManager em = FonteDados.createEntityManager();
    private final LugarDao ldao = new LugarDao(em);
    private Lugar lugar;
    private final CidadeDao cdao = new CidadeDao(em);
    private Cidade cidade;
    private final EventoDao edao = new EventoDao(em);
    private Evento evento;
    /**
     * Creates new form LugarInserir
     */
    public LugarExcluir() {
        initComponents();
        
        List<Cidade> lCidade = cdao.findAll();
        for (Cidade c : lCidade) {
            cbxCidade.addItem(c.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLugar = new javax.swing.JLabel();
        cbxLugar = new javax.swing.JComboBox<>();
        btnExcluir = new javax.swing.JButton();
        lblCidade = new javax.swing.JLabel();
        cbxCidade = new javax.swing.JComboBox<>();
        btnBuscarCidade = new javax.swing.JButton();
        btnBuscarLugar = new javax.swing.JButton();
        txtTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblLugar.setText("Lugar:");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblCidade.setText("Cidade:");

        btnBuscarCidade.setText("Buscar");
        btnBuscarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCidadeActionPerformed(evt);
            }
        });

        btnBuscarLugar.setText("Buscar");
        btnBuscarLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblLugar)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipo)
                            .addComponent(cbxLugar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarCidade)
                    .addComponent(btnBuscarLugar))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btnExcluir)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCidade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLugar)
                    .addComponent(cbxLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarLugar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnExcluir)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCidadeActionPerformed
        // TODO add your handling code here:
        cidade = cdao.findByKey(cbxCidade.getSelectedItem().toString());
        //Fazer o tratamento pra pegar só lugar
        cbxLugar.removeAllItems();
        List<Construcao> lConstrucao = cidade.getConstrucoes();
        for (Construcao c : lConstrucao) {
            if(c instanceof Lugar)
                cbxLugar.addItem(""+c.getCodigo());
        }
        
    }//GEN-LAST:event_btnBuscarCidadeActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        List<Evento> lEvento = edao.findAll();
        for (Evento e : lEvento) {
            if(e.getLocal() == lugar){
                e.setLocal(null);
                edao.update(e);
            }
        }

        cidade.getConstrucoes().remove(lugar);
        

        ldao.delete(lugar);
        cdao.update(cidade);

        JOptionPane.showMessageDialog(this, "Lugar Excluido.");

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLugarActionPerformed
        // TODO add your handling code here:
        lugar = ldao.findByKey(Integer.parseInt(cbxLugar.getSelectedItem().toString()));
        txtTipo.setEditable(false);
        txtTipo.setText(lugar.getLugar().toString());
    }//GEN-LAST:event_btnBuscarLugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCidade;
    private javax.swing.JButton btnBuscarLugar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<String> cbxCidade;
    private javax.swing.JComboBox<String> cbxLugar;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblLugar;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
