/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.cco006.thesims.view;

import br.edu.unifei.cco006.thesims.dao.CidadeDao;
import br.edu.unifei.cco006.thesims.dao.FonteDados;
import br.edu.unifei.cco006.thesims.dao.LugarDao;
import br.edu.unifei.cco006.thesims.modelo.Cidade;
import br.edu.unifei.cco006.thesims.modelo.Lugar;
import br.edu.unifei.cco006.thesims.modelo.LugarEnum;
import java.time.LocalDateTime;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class LugarInserir extends javax.swing.JFrame {

    private final EntityManager em = FonteDados.createEntityManager();
    private final LugarDao ldao = new LugarDao(em);
    private Lugar lugar;
    private final CidadeDao cdao = new CidadeDao(em);
    private Cidade cidade;
    
    /**
     * Creates new form LugarInserir
     */
    public LugarInserir() {
        initComponents();
        
        List<Cidade> lCidade = cdao.findAll();
        for (Cidade c : lCidade) {
            cbxCidade.addItem(c.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOpen = new javax.swing.JLabel();
        txtOpen = new javax.swing.JTextField();
        lblClose = new javax.swing.JLabel();
        txtClose = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        btnInserir = new javax.swing.JButton();
        lblCidade = new javax.swing.JLabel();
        cbxCidade = new javax.swing.JComboBox<>();
        btnBuscarCidade = new javax.swing.JButton();
        lblExemplo = new javax.swing.JLabel();
        lblFormato = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblOpen.setText("Open:");

        lblClose.setText("Close:");

        lblTipo.setText("Tipo:");

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACAMPAMENTO", "IGREJA", "BAR", "RESTAURANTE", "SHOPPING", "SPA", "PRACA", "HOSPITAL", "ESCOLA", "ACADEMIA" }));

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        lblCidade.setText("Cidade:");

        btnBuscarCidade.setText("Buscar");
        btnBuscarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCidadeActionPerformed(evt);
            }
        });

        lblExemplo.setText("2017-11-18T18:45:00");

        lblFormato.setText("Formato:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnInserir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblClose)
                                .addComponent(lblOpen)
                                .addComponent(lblFormato))
                            .addComponent(lblTipo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOpen)
                            .addComponent(txtClose)
                            .addComponent(cbxTipo, 0, 141, Short.MAX_VALUE)
                            .addComponent(lblExemplo))))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarCidade)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCidade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExemplo)
                    .addComponent(lblFormato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpen)
                    .addComponent(txtOpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClose)
                    .addComponent(txtClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInserir)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        
        lugar = new Lugar();
         if(cbxTipo.getSelectedItem().toString().equals("ACADEMIA")) {
            lugar.setLugar(LugarEnum.ACADEMIA);
        } else if(cbxTipo.getSelectedItem().toString().equals("ACAMPAMENTO")) {
            lugar.setLugar(LugarEnum.ACAMPAMENTO);
        }else if(cbxTipo.getSelectedItem().toString().equals("BAR")) {
            lugar.setLugar(LugarEnum.BAR);
        }else if(cbxTipo.getSelectedItem().toString().equals("ESCOLA")) {
            lugar.setLugar(LugarEnum.ESCOLA);
        }else if(cbxTipo.getSelectedItem().toString().equals("HOSPITAL")) {
            lugar.setLugar(LugarEnum.HOSPITAL);
        }else if(cbxTipo.getSelectedItem().toString().equals("IGREJA")) {
            lugar.setLugar(LugarEnum.IGREJA);
        }else if(cbxTipo.getSelectedItem().toString().equals("PRACA")) {
            lugar.setLugar(LugarEnum.PRACA);
        }else if(cbxTipo.getSelectedItem().toString().equals("RESTAURANTE")) {
            lugar.setLugar(LugarEnum.RESTAURANTE);
        } else if(cbxTipo.getSelectedItem().toString().equals("SHOPPING")) {
            lugar.setLugar(LugarEnum.SHOPPING);
        }else if(cbxTipo.getSelectedItem().toString().equals("SPA")) {
            lugar.setLugar(LugarEnum.SPA);
        }
         //formato: 2017-11-18T18:45:00
         lugar.setOpen(LocalDateTime.parse(txtOpen.getText()));
         lugar.setClose(LocalDateTime.parse(txtClose.getText()));
         
         ldao.create(lugar);
         cidade.getConstrucoes().add(lugar);
         cdao.update(cidade);
         
         JOptionPane.showMessageDialog(this, "Lugar criado.");
         
        
        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnBuscarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCidadeActionPerformed
        // TODO add your handling code here:
        cidade = cdao.findByKey(cbxCidade.getSelectedItem().toString());
        
    }//GEN-LAST:event_btnBuscarCidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCidade;
    private javax.swing.JButton btnInserir;
    private javax.swing.JComboBox<String> cbxCidade;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblExemplo;
    private javax.swing.JLabel lblFormato;
    private javax.swing.JLabel lblOpen;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtClose;
    private javax.swing.JTextField txtOpen;
    // End of variables declaration//GEN-END:variables
}
