/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.cco006.thesims.view;

import br.edu.unifei.cco006.thesims.dao.CasaDao;
import br.edu.unifei.cco006.thesims.dao.ComodoDao;
import br.edu.unifei.cco006.thesims.dao.FonteDados;
import br.edu.unifei.cco006.thesims.dao.ObjetoDao;
import br.edu.unifei.cco006.thesims.modelo.Casa;
import br.edu.unifei.cco006.thesims.modelo.Comodo;
import br.edu.unifei.cco006.thesims.modelo.Objeto;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class ObjetoExcluir extends javax.swing.JFrame {
    
    private final EntityManager em = FonteDados.createEntityManager();
    private final ObjetoDao odao = new ObjetoDao(em);
    private Objeto objeto;
    private final ComodoDao cdao = new ComodoDao(em);
    private Comodo comodo;
    private final CasaDao casaDao = new CasaDao(em);
    private Casa casa;
    
    
    /**
     * Creates new form ComodoInserir
     */
    public ObjetoExcluir() {
        initComponents();
        
        List<Integer> l = casaDao.buscaCasa();
        for (int cod : l) {
            cbxCasa.addItem(""+cod);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        cbxObjeto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbxCasa = new javax.swing.JComboBox<>();
        btnExcluir = new javax.swing.JButton();
        lblComodo = new javax.swing.JLabel();
        cbxComodo = new javax.swing.JComboBox<>();
        btnBuscarComodo = new javax.swing.JButton();
        btnBuscarCasa = new javax.swing.JButton();
        txtComodo = new javax.swing.JTextField();
        btnBuscarObjeto = new javax.swing.JButton();
        txtObjeto = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTipo.setText("Objeto:");

        jLabel1.setText("Casa:");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblComodo.setText("Comodo:");

        btnBuscarComodo.setText("Buscar");
        btnBuscarComodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarComodoActionPerformed(evt);
            }
        });

        btnBuscarCasa.setText("Buscar");
        btnBuscarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCasaActionPerformed(evt);
            }
        });

        btnBuscarObjeto.setText("Buscar");
        btnBuscarObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarObjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComodo)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxComodo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipo)
                        .addGap(18, 18, 18)
                        .addComponent(cbxObjeto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarComodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComodo, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarCasa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExcluir)
                            .addComponent(btnBuscarObjeto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtObjeto)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCasa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComodo)
                    .addComponent(cbxComodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarComodo)
                    .addComponent(txtComodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cbxObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarObjeto)
                    .addComponent(txtObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnExcluir)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        comodo.getObjetos().remove(objeto);
        cdao.update(comodo);
        casaDao.update(casa);
        odao.delete(objeto);

        
        JOptionPane.showMessageDialog(
                this, " Objeto excluido.");
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCasaActionPerformed
        // TODO add your handling code here:
        casa = casaDao.findByKey(Integer.parseInt(cbxCasa.getSelectedItem().toString()));
        
        cbxComodo.removeAllItems();
        List<Comodo> lComodo = casa.getComodo();
        for (Comodo c : lComodo) {
            cbxComodo.addItem(""+c.getCodigo());
        }
        
    }//GEN-LAST:event_btnBuscarCasaActionPerformed

    private void btnBuscarComodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarComodoActionPerformed
        // TODO add your handling code here:
        comodo = cdao.findByKey(Integer.parseInt(cbxComodo.getSelectedItem().toString()));
        txtComodo.setEditable(false);
        txtComodo.setText(comodo.getComodo().toString());
        
        cbxObjeto.removeAllItems();
        List<Objeto> lObjeto = comodo.getObjetos();
        for (Objeto o : lObjeto) {
            cbxObjeto.addItem(""+o.getCodigo());
        }
        
    }//GEN-LAST:event_btnBuscarComodoActionPerformed

    private void btnBuscarObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarObjetoActionPerformed
        // TODO add your handling code here:
        objeto = odao.findByKey(Integer.parseInt(cbxObjeto.getSelectedItem().toString()));
        txtObjeto.setEditable(false);
        txtObjeto.setText(objeto.getObjeto().toString());
    }//GEN-LAST:event_btnBuscarObjetoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCasa;
    private javax.swing.JButton btnBuscarComodo;
    private javax.swing.JButton btnBuscarObjeto;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<String> cbxCasa;
    private javax.swing.JComboBox<String> cbxComodo;
    private javax.swing.JComboBox<String> cbxObjeto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblComodo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtComodo;
    private javax.swing.JTextField txtObjeto;
    // End of variables declaration//GEN-END:variables
}
