/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.cco006.thesims.view;

import br.edu.unifei.cco006.thesims.dao.CasaDao;
import br.edu.unifei.cco006.thesims.dao.ComodoDao;
import br.edu.unifei.cco006.thesims.dao.FamiliaDao;
import br.edu.unifei.cco006.thesims.dao.FonteDados;
import br.edu.unifei.cco006.thesims.dao.PessoaDao;
import br.edu.unifei.cco006.thesims.modelo.Casa;
import br.edu.unifei.cco006.thesims.modelo.Comodo;
import br.edu.unifei.cco006.thesims.modelo.Familia;
import br.edu.unifei.cco006.thesims.modelo.Pessoa;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class PessoaExcluir extends javax.swing.JFrame {

    /**
     * Creates new form FamiliaAlterar
    */
    
    private final EntityManager em = FonteDados.createEntityManager();
    private final PessoaDao pdao = new PessoaDao(em);
    private Pessoa pessoa;
    private final FamiliaDao fdao = new FamiliaDao(em);
    private Familia familia;
    private Pessoa pai, mae, conjuge;

    
    public PessoaExcluir() {
        initComponents();
        
        List<String> lFamilia = fdao.buscaFamilia();
        for (String string : lFamilia) {
            cbxFamilia.addItem(string);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFamilia = new javax.swing.JLabel();
        cbxFamilia = new javax.swing.JComboBox<>();
        btnBuscarPessoa = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblPessoa = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        cbxPessoa = new javax.swing.JComboBox<>();
        txtNome = new javax.swing.JTextField();
        btnBuscarFamilia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFamilia.setText("Familia:");

        btnBuscarPessoa.setText("Buscar");
        btnBuscarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPessoaActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblPessoa.setText("Pessoa:");

        lblNome.setText("Nome:");

        btnBuscarFamilia.setText("Buscar");
        btnBuscarFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFamiliaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblFamilia)
                        .addComponent(lblPessoa))
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxFamilia, 0, 151, Short.MAX_VALUE)
                    .addComponent(btnExcluir)
                    .addComponent(cbxPessoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNome))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarPessoa)
                    .addComponent(btnBuscarFamilia))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFamilia)
                    .addComponent(cbxFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarFamilia))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarPessoa)
                    .addComponent(lblPessoa)
                    .addComponent(cbxPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnExcluir)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPessoaActionPerformed
        // TODO add your handling code here:
         
         pessoa = pdao.findByKey(Integer.parseInt(cbxPessoa.getSelectedItem().toString()));
         txtNome.setText(pessoa.getNome());
         btnExcluir.setEnabled(true);        
    }//GEN-LAST:event_btnBuscarPessoaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
       
        //para todas as pessoas que possuem a que quer excluir como filho, remove e atualiza
        List<Pessoa> lPessoas = pdao.findAll();
        for (Pessoa p : lPessoas) {
            List<Pessoa> filhos = p.getFilhos();
            for (Pessoa f : filhos) {
                if(pessoa == f){
                    filhos.remove(pessoa);
                }
            }
            //se a pessoa tem como conjuge a que quer excluir, remove e atualiza
            if(p.getConjuge() == pessoa){
                p.setConjuge(null);
            }
            pdao.update(p);
        }
        
        familia.getMembros().remove(pessoa);
        fdao.update(familia);
        
        pdao.delete(pessoa);
        
        
        cbxFamilia.setEnabled(true);
        btnBuscarFamilia.setEnabled(true);
        btnExcluir.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Pessoa excluida. ");
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFamiliaActionPerformed
        // TODO add your handling code here:
        cbxPessoa.removeAllItems();
        familia = fdao.findByKey(cbxFamilia.getSelectedItem().toString());
        
        
        List<Pessoa> lPessoa = familia.getMembros();
        for (Pessoa p : lPessoa) {
            cbxPessoa.addItem(""+p.getCodigo());
        }
        cbxFamilia.setEnabled(false);
        btnBuscarFamilia.setEnabled(false);
        
    }//GEN-LAST:event_btnBuscarFamiliaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFamilia;
    private javax.swing.JButton btnBuscarPessoa;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<String> cbxFamilia;
    private javax.swing.JComboBox<String> cbxPessoa;
    private javax.swing.JLabel lblFamilia;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPessoa;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
