/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.cco006.thesims.view;

import br.edu.unifei.cco006.thesims.dao.FamiliaDao;
import br.edu.unifei.cco006.thesims.dao.FonteDados;
import br.edu.unifei.cco006.thesims.dao.PessoaDao;
import br.edu.unifei.cco006.thesims.modelo.Familia;
import br.edu.unifei.cco006.thesims.modelo.Pessoa;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author maria
 */
public class PessoaInserir extends javax.swing.JFrame {

    
    private final EntityManager em = FonteDados.createEntityManager();
    private final PessoaDao pdao = new PessoaDao(em);
    private Pessoa pessoa;
    private final FamiliaDao fdao = new FamiliaDao(em);
    private Familia familia;
    private Pessoa pai, mae, conjuge;
    
    /**
     * Creates new form PessoaInserir
     */
    public PessoaInserir() {
        initComponents();
        
        List<String> lFamilia = fdao.buscaFamilia();
        for (String string : lFamilia) {
            cbxFamilia.addItem(string);
        }
        
        inicializaCbx();
                
    }
    
    
    private void inicializaCbx(){
        cbxPai.removeAllItems();
        List<Integer> buscaPai = pdao.buscaPessoa();
        for (Integer integer : buscaPai) {
            cbxPai.addItem(integer.toString());
        }
        
         cbxMae.removeAllItems();
        List<Integer> buscaMae = pdao.buscaPessoa();
        for (Integer integer : buscaMae) {
            cbxMae.addItem(integer.toString());
        }
        
        cbxConjuge.removeAllItems();
        List<Integer> buscaConjuge = pdao.buscaPessoa();
        for (Integer integer : buscaConjuge) {
            cbxConjuge.addItem(integer.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFamilia = new javax.swing.JLabel();
        cbxFamilia = new javax.swing.JComboBox<>();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblIdade = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        corPele = new javax.swing.JLabel();
        txtCorPele = new javax.swing.JTextField();
        lblCorOlho = new javax.swing.JLabel();
        txtCorOlho = new javax.swing.JTextField();
        lblCorCabelo = new javax.swing.JLabel();
        txtCorCabelo = new javax.swing.JTextField();
        lblPai = new javax.swing.JLabel();
        cbxPai = new javax.swing.JComboBox<>();
        lblMae = new javax.swing.JLabel();
        cbxMae = new javax.swing.JComboBox<>();
        lblConjuge = new javax.swing.JLabel();
        cbxConjuge = new javax.swing.JComboBox<>();
        btnInserir = new javax.swing.JButton();
        btnBuscarPai = new javax.swing.JButton();
        btnBuscarMae = new javax.swing.JButton();
        txtPai = new javax.swing.JTextField();
        txtMae = new javax.swing.JTextField();
        btnBuscarConjuge = new javax.swing.JButton();
        txtConjuge = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFamilia.setText("Família");

        lblNome.setText("Nome:");

        lblIdade.setText("Idade:");

        lblSexo.setText("Sexo:");

        corPele.setText("Cor pele:");

        lblCorOlho.setText("Cor olho:");

        lblCorCabelo.setText("Cor cabelo:");

        lblPai.setText("Pai:");

        lblMae.setText("Mãe:");

        lblConjuge.setText("Cônjuge:");

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnBuscarPai.setText("Buscar");
        btnBuscarPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPaiActionPerformed(evt);
            }
        });

        btnBuscarMae.setText("Buscar");
        btnBuscarMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMaeActionPerformed(evt);
            }
        });

        btnBuscarConjuge.setText("Buscar");
        btnBuscarConjuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConjugeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome)
                        .addGap(18, 18, 18)
                        .addComponent(lblIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFamilia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCorCabelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorCabelo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblConjuge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarConjuge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConjuge)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(corPele)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorPele, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCorOlho)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtCorOlho, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMae)
                                    .addComponent(lblPai))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxPai, 0, 93, Short.MAX_VALUE)
                                    .addComponent(cbxMae, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscarMae))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(btnBuscarPai)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMae, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addComponent(txtPai))
                                .addGap(30, 30, 30))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btnInserir)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFamilia)
                    .addComponent(cbxFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdade)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorCabelo)
                    .addComponent(txtCorCabelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corPele)
                    .addComponent(txtCorPele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorOlho)
                    .addComponent(txtCorOlho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPai)
                    .addComponent(cbxPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPai)
                    .addComponent(txtPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMae)
                    .addComponent(cbxMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMae)
                    .addComponent(txtMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConjuge)
                    .addComponent(cbxConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarConjuge)
                    .addComponent(txtConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnInserir)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:

       
        
        
        pessoa = new Pessoa();
        pessoa.setNome(txtNome.getText());
        pessoa.setIdade(Integer.parseInt(txtIdade.getText()));
        pessoa.setSexo(txtSexo.getText());
        pessoa.setCorCabelo(txtCorCabelo.getText());
        pessoa.setCorPele(txtCorPele.getText());
        pessoa.setCorOlho(txtCorOlho.getText());
        
        familia = fdao.findByKey(cbxFamilia.getSelectedItem().toString());
        familia.getMembros().add(pessoa);
        
        if(conjuge!=null){
            pessoa.setConjuge(conjuge);
        }
        
        pdao.create(pessoa);
        
        if(pai!= null){
            pai.getFilhos().add(pessoa);
             pdao.update(pai);
        }
        
        if(mae!=null){
            mae.getFilhos().add(pessoa);
            pdao.update(mae);
        }

        
        
        
        fdao.update(familia);
        
        txtConjuge.setText("");
        txtCorCabelo.setText("");
        txtCorOlho.setText("");
        txtCorPele.setText("");
        txtIdade.setText("");
        txtMae.setText("");
        txtNome.setText("");
        txtPai.setText("");
        txtSexo.setText("");
        
         JOptionPane.showMessageDialog(
                this, "Pessoa "+ pessoa.getNome() + " criada. ");
              
         inicializaCbx();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnBuscarPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPaiActionPerformed
        // TODO add your handling code here:
        pai = pdao.findByKey(Integer.parseInt(cbxPai.getSelectedItem().toString()));
        txtPai.setText(pai.getNome());
    }//GEN-LAST:event_btnBuscarPaiActionPerformed

    private void btnBuscarMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMaeActionPerformed
        // TODO add your handling code here:
        mae = pdao.findByKey(Integer.parseInt(cbxMae.getSelectedItem().toString()));
        txtMae.setText(mae.getNome());
    }//GEN-LAST:event_btnBuscarMaeActionPerformed

    private void btnBuscarConjugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConjugeActionPerformed
        // TODO add your handling code here:
        conjuge = pdao.findByKey(Integer.parseInt(cbxConjuge.getSelectedItem().toString()));
        txtConjuge.setText(conjuge.getNome());
    }//GEN-LAST:event_btnBuscarConjugeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarConjuge;
    private javax.swing.JButton btnBuscarMae;
    private javax.swing.JButton btnBuscarPai;
    private javax.swing.JButton btnInserir;
    private javax.swing.JComboBox<String> cbxConjuge;
    private javax.swing.JComboBox<String> cbxFamilia;
    private javax.swing.JComboBox<String> cbxMae;
    private javax.swing.JComboBox<String> cbxPai;
    private javax.swing.JLabel corPele;
    private javax.swing.JLabel lblConjuge;
    private javax.swing.JLabel lblCorCabelo;
    private javax.swing.JLabel lblCorOlho;
    private javax.swing.JLabel lblFamilia;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblMae;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPai;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JTextField txtConjuge;
    private javax.swing.JTextField txtCorCabelo;
    private javax.swing.JTextField txtCorOlho;
    private javax.swing.JTextField txtCorPele;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtMae;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPai;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
