/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.cco006.thesims.view;

import br.edu.unifei.cco006.thesims.dao.CasaDao;
import br.edu.unifei.cco006.thesims.dao.ComodoDao;
import br.edu.unifei.cco006.thesims.dao.FonteDados;
import br.edu.unifei.cco006.thesims.dao.PessoaDao;
import br.edu.unifei.cco006.thesims.dao.RelacionamentoDao;
import br.edu.unifei.cco006.thesims.modelo.Casa;
import br.edu.unifei.cco006.thesims.modelo.Comodo;
import br.edu.unifei.cco006.thesims.modelo.Lazer;
import br.edu.unifei.cco006.thesims.modelo.LazerEnum;
import br.edu.unifei.cco006.thesims.modelo.Objeto;
import br.edu.unifei.cco006.thesims.modelo.Pessoa;
import br.edu.unifei.cco006.thesims.modelo.Relacionamento;
import br.edu.unifei.cco006.thesims.modelo.RelacionamentoEnum;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class RelacionamentoInserir extends javax.swing.JFrame {

    private final EntityManager em = FonteDados.createEntityManager();
    private final RelacionamentoDao rdao = new RelacionamentoDao(em);
    private Relacionamento relacionamento;    
    private final PessoaDao pdao = new PessoaDao(em);
    private Pessoa pessoa;
    private Pessoa interlocutor;
    private final CasaDao casaDao = new CasaDao(em);
    private Casa casa;
    private final ComodoDao cdao = new ComodoDao(em);
    private Comodo comodo;
    
    /**
     * Creates new form AlimentarInserir
     */
    public RelacionamentoInserir() {
        initComponents();
        
        List<Pessoa> lPessoa = pdao.findAll();
        for (Pessoa p : lPessoa) {
            cbxPessoa.addItem(""+p.getCodigo());
        }
        
        List<Casa> lCasa = casaDao.findAll();
        for (Casa c : lCasa) {
            cbxCasa.addItem(""+c.getCodigo());
        }
        
         List<Pessoa> lPessoa2 = pdao.findAll();
        for (Pessoa p : lPessoa2){
            cbxInterlocutor.addItem(""+p.getCodigo());
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPessoa = new javax.swing.JLabel();
        cbxPessoa = new javax.swing.JComboBox<>();
        btnBuscarPessoa = new javax.swing.JButton();
        txtPessoa = new javax.swing.JTextField();
        lblLazer = new javax.swing.JLabel();
        cbxAcao = new javax.swing.JComboBox<>();
        lblComodo = new javax.swing.JLabel();
        txtComodo = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        lblCasa = new javax.swing.JLabel();
        cbxCasa = new javax.swing.JComboBox<>();
        btnBuscarCasa = new javax.swing.JButton();
        cbxComodo = new javax.swing.JComboBox<>();
        btnBuscarComodo = new javax.swing.JButton();
        lblInterlocutor = new javax.swing.JLabel();
        cbxInterlocutor = new javax.swing.JComboBox<>();
        btnBuscarInterlocutor = new javax.swing.JButton();
        txtInterlocutor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblPessoa.setText("Pessoa:");

        btnBuscarPessoa.setText("Buscar");
        btnBuscarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPessoaActionPerformed(evt);
            }
        });

        lblLazer.setText("Ação:");

        cbxAcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONVERSAR", "DISCUTIR", "AFETO", "BRIGAR" }));

        lblComodo.setText("Comodo:");

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        lblCasa.setText("Casa:");

        btnBuscarCasa.setText("Buscar");
        btnBuscarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCasaActionPerformed(evt);
            }
        });

        btnBuscarComodo.setText("Buscar");
        btnBuscarComodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarComodoActionPerformed(evt);
            }
        });

        lblInterlocutor.setText("Interlocutor");

        btnBuscarInterlocutor.setText("Buscar");
        btnBuscarInterlocutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInterlocutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btnInserir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInterlocutor)
                    .addComponent(lblLazer)
                    .addComponent(lblPessoa)
                    .addComponent(lblCasa)
                    .addComponent(lblComodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPessoa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxComodo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarComodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtComodo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarCasa)))
                        .addGap(0, 139, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxInterlocutor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarInterlocutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtInterlocutor)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPessoa)
                    .addComponent(cbxPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPessoa)
                    .addComponent(txtPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLazer)
                    .addComponent(cbxAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCasa)
                    .addComponent(cbxCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCasa))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComodo)
                    .addComponent(txtComodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxComodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarComodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInterlocutor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxInterlocutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarInterlocutor)
                        .addComponent(txtInterlocutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnInserir)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPessoaActionPerformed
        // TODO add your handling code here:
        pessoa = pdao.findByKey(Integer.parseInt(cbxPessoa.getSelectedItem().toString()));
        txtPessoa.setEditable(false);
        txtPessoa.setText(pessoa.getNome());
    }//GEN-LAST:event_btnBuscarPessoaActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        
       relacionamento = new Relacionamento();
        
      
        if(cbxAcao.getSelectedItem().toString().equals("AFETO")) {
            relacionamento.setAcao(RelacionamentoEnum.AFETO);
        } else if(cbxAcao.getSelectedItem().toString().equals("BRIGAR")) {
            relacionamento.setAcao(RelacionamentoEnum.BRIGAR);
        } else if(cbxAcao.getSelectedItem().toString().equals("CONVERSAR")) {
            relacionamento.setAcao(RelacionamentoEnum.CONVERSAR);
        } else if(cbxAcao.getSelectedItem().toString().equals("DISCUTIR")) {
            relacionamento.setAcao(RelacionamentoEnum.DISCUTIR);
        } 
        
        relacionamento.setInterlocutor(interlocutor);
        relacionamento.setComodo(comodo);
        rdao.create(relacionamento);
        
        pessoa.getAcoes().add(relacionamento);
        pdao.update(pessoa);
               
        txtComodo.setText("");
        txtPessoa.setText("");
        txtInterlocutor.setText("");
        
        JOptionPane.showMessageDialog(this, pessoa.getNome()+ " " + relacionamento.getAcao().toString());
        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnBuscarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCasaActionPerformed
        // TODO add your handling code here:
        casa = casaDao.findByKey(Integer.parseInt(cbxCasa.getSelectedItem().toString()));
        
        //cbxDestino.removeAllItems();
        List<Comodo> lComodo = casa.getComodo();
        for (Comodo c : lComodo) {
            cbxComodo.addItem(""+c.getCodigo());
        }
    }//GEN-LAST:event_btnBuscarCasaActionPerformed

    private void btnBuscarComodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarComodoActionPerformed
        // TODO add your handling code here:
        comodo = cdao.findByKey(Integer.parseInt(cbxComodo.getSelectedItem().toString()));
        txtComodo.setEditable(false);
        txtComodo.setText(comodo.getComodo().toString());        
    }//GEN-LAST:event_btnBuscarComodoActionPerformed

    private void btnBuscarInterlocutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInterlocutorActionPerformed
        // TODO add your handling code here:
        interlocutor = pdao.findByKey(Integer.parseInt(cbxInterlocutor.getSelectedItem().toString()));
        txtInterlocutor.setEditable(false);
        txtInterlocutor.setText(interlocutor.getNome());
    }//GEN-LAST:event_btnBuscarInterlocutorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCasa;
    private javax.swing.JButton btnBuscarComodo;
    private javax.swing.JButton btnBuscarInterlocutor;
    private javax.swing.JButton btnBuscarPessoa;
    private javax.swing.JButton btnInserir;
    private javax.swing.JComboBox<String> cbxAcao;
    private javax.swing.JComboBox<String> cbxCasa;
    private javax.swing.JComboBox<String> cbxComodo;
    private javax.swing.JComboBox<String> cbxInterlocutor;
    private javax.swing.JComboBox<String> cbxPessoa;
    private javax.swing.JLabel lblCasa;
    private javax.swing.JLabel lblComodo;
    private javax.swing.JLabel lblInterlocutor;
    private javax.swing.JLabel lblLazer;
    private javax.swing.JLabel lblPessoa;
    private javax.swing.JTextField txtComodo;
    private javax.swing.JTextField txtInterlocutor;
    private javax.swing.JTextField txtPessoa;
    // End of variables declaration//GEN-END:variables
}
